### PR TITLE
Fix unused return type for generators

### LINKED ISSUE #71: `UnusedReturnType` for `Generator`
Howdy!

This code:

```php
function f(): Generator {
    yield 42;
}
```

will throw this error: `PHPCS.E.NeutronStandard.Functions.TypeHint.UnusedReturnType` saying:

> Return type with no return

Yes, there is no `return` statement, but we have a `yield` ;-).

### PR DESCRIPTION
**Pull request by yoavf**
`yield` is a valid keyword that acts as a return for generator functions.

Fixes #71

### CODE REVIEW

File: NeutronStandard/SniffHelpers.php [hunk 1]
```diff
@@ -55,7 +55,7 @@ public function getArgumentTypePtr(File $phpcsFile, $stackPtr) {
 
 	public function isReturnValueVoid(File $phpcsFile, $stackPtr) {
 		$tokens = $phpcsFile->getTokens();
-		if ($tokens[$stackPtr]['code'] !== T_RETURN) {
+		if (! in_array( $tokens[$stackPtr]['code'], [T_RETURN, T_YIELD], false)) {
```
Comment (sirbrillig) [inline NeutronStandard/SniffHelpers.php]: I wish we had prettier for PHP 😩 . There's an extra space here after the first paren in `in_array(`. If you set your editor to use the phpcs config in this project you'll see a `PSR2.Methods.FunctionCallSignature.SpaceAfterOpenBracket` error here. I should set up this repository to automatically run linting in the CI.

File: NeutronStandard/Sniffs/Functions/TypeHintSniff.php [hunk 2]
```diff
@@ -64,7 +64,7 @@ private function checkForMissingReturnHints(File $phpcsFile, $stackPtr, SniffHel
 			if ($token['code'] === T_CLOSURE) {
 				array_unshift($scopeClosers, $token['scope_closer']);
 			}
-			if (empty($scopeClosers) && $token['code'] === T_RETURN) {
+			if (empty($scopeClosers) && in_array( $token['code'], [T_RETURN, T_YIELD], true)) {
```
Comment (sirbrillig) [inline NeutronStandard/Sniffs/Functions/TypeHintSniff.php]: Same spacing error here.

**Review by sirbrillig — COMMENTED** [review]
Thanks! This works as described. It does introduce a couple of really minor spacing issues, though, which I've marked. I just added linting to the CI setup in #80 which is not quite as good as prettier but will at least mark these things automatically in the future.
